apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
  namespace: tekton-pipelines-secure
spec:
  params:
    - name: url
      type: string
      default: "https://github.com/SajjanYadav/Budget-App.git"
    - name: tag
      type: string
      default: "sajjany/budget-app:latest"
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: url
          value: $(params.url)
        - name: tag
          value: $(params.tag)

